model:
  backbone: resnet50
  pretrained_backbone: true
  input_size: 640

training:
  epochs: 50
  batch_size: 8
  num_workers: 4
  lr: 0.001
  backbone_lr: 0.0001
  weight_decay: 0.0005
  warmup_epochs: 5
  val_interval: 5

inference:
  confidence: 0.01 # 0.25
  iou: 0.60 # 0.50

loss:
  box: 7.5
  cls: 0.5
  dfl: 1.5

augmentation:
  flip_lr: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  translate: 0.10
  scale: 0.20
